version: '3'

services:
  fastapi:
    build:
      context: api/
      dockerfile: Dockerfile
    command: sh -c "gunicorn main:app --timeout 6000 --bind 0.0.0.0:5000 -w 1 -k uvicorn.workers.UvicornWorker"
    environment:
      - "PYTHONUNBUFFERED=1"
      - "GENE_SEARCH_BASE_URI"
    ports:
      - "5000:5000"
    volumes:
      - "/data/proj/lit-explore/pubtator/2023-11-06/:/data"
  node:
    build:
      context: node/
      dockerfile: Dockerfile
    command: "yarn start"
    environment:
      - "REACT_APP_GENE_SEARCH_BASE_URI=${GENE_SEARCH_BASE_URI}"
    user: "node"
    working_dir: /home/node/app
    ports:
      - "81:81"
